config/routes.rb
Rails.application.routes.draw do

  root 'todos#index'

  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  resources :users do
    resources :todos
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'bcrypt'
  
  attr_accessor :password
  before_save :encrypt_password

  validates :password, presence: true, confirmation: true, on: :create
  validates :email, presence: true, uniqueness: true

  private

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user

  protected

  def authenticate_user
    redirect_to sign_up_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    session[:user] = nil
    redirect_to root_url, notice: 'Logged out'
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
	  @todos = Todo.all
	end
	
	
	def new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def show
		@todo = Todo.find params[:id]
	end
	
	private

	def todo_params
		params.require(:todo).permit(:task_description, :due_date)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate_user
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user.id
      redirect_to user_todos_path(current_user), notice: 'User created'
    else
      flash[:error] = 'User creation failed'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todolists/index.html.erb
<%= link_to 'New task', new_todo_path %>

app/views/todolists/new.html.erb
<%= form_for Todolist.new do |form| %>
	<%= form.text_field :description, placeholder: 'Task Description' %>
	<%= form.text_field :daysleft, placeholder: 'Days left' %>
	<%= form.text_field :complete, placeholder: 'Complete' %>
	<%= form.submit 'Save' %>
<% end %>

app/views/todolists/show.html.erb
<h1>To Do List</h1>

<%= click('Todo') %>

app/views/todos/index.html.erb
<h3>All todos</h3>

<% @todos.each do |todo| %>
  <%= div_for(todo) do %>
    <p><%= todo.task_description %></p>
    <p>Due at: <%= todo.due_date.strftime('%A, %b %d') %></p>
    <%= link_to 'Mark complete' %>
  <% end %>
<% end %>

<%#= link_to 'New task', new_todo_path %>

app/views/todos/new.html.erb
<%= form_for Todo.new do |form| %>
	<%= form.text_field :task_description, placeholder: 'Task Description' %>
	<%= form.date_select :due_date, default: 7.days.from_now, placeholder: 'Duedate' %>
  <%= form.submit 'Save' %>
<% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.task_description %></b></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<%= form.submit 'Sign In' %>